[package]
name = "fusion-node"
version.workspace = true
edition.workspace = true

[lib]
name = "fusion_node"
crate-type = ["cdylib"]

[dependencies]
fusion-core = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }

[build-dependencies]
napi-build = "2"
