/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getHttpMethods(): Array<string>
export declare function apiResourceNameJs(className: string): string
export declare function resolveRoutePathJs(template: string, className: string): string
export declare function coerceParamJs(raw: string, kind?: string | undefined | null): unknown
export interface HttpStatusCode {
  name: string
  code: number
}
export declare function getHttpStatusCodes(): Array<HttpStatusCode>
export interface HttpHeaderConstant {
  name: string
  value: string
}
export declare function getHttpHeaderConstants(): Array<HttpHeaderConstant>
export declare function headerAttachment(filename: string): Record<string, string>
export declare function headerInline(filename?: string | undefined | null): Record<string, string>
export declare function headerContentType(mediaType: string, charset?: string | undefined | null): Record<string, string>
export declare function headerLocation(url: string): Record<string, string>
export declare function headerCacheControl(value: string): Record<string, string>
export declare function headerDownload(filename: string, mediaType?: string | undefined | null): Record<string, string>
export declare function getFingerprintHeaders(): Record<string, string>
/** True when the client prefers JSON (`Accept` or `?format=json`). */
export declare function prefersJsonJs(accept?: string | undefined | null, formatQuery?: string | undefined | null): boolean
/** Render a Tera template file relative to `templates_root` (default `"templates"`). */
export declare function renderTemplateJs(templateName: string, context: JsJson, templatesRoot?: string | undefined | null): string
export interface PaginationParams {
  page: number
  pageSize: number
  offset: number
}
export declare function parsePagination(query: object, defaultPageSize?: number | undefined | null, maxPageSize?: number | undefined | null): PaginationParams
export declare function paginatedBody(items: unknown, total: number, params: PaginationParams): unknown
/** Apply `cache.*` from a Settings instance to the process-wide cache. */
export declare function cacheConfigure(settings: Settings): void
/** Install a driver explicitly (default moka). */
export declare function cacheConfigureDriver(driver?: string | undefined | null, maxCapacity?: number | undefined | null, defaultTtl?: number | undefined | null): void
export declare function cacheSet(key: string, value: JsJson, ttl?: number | undefined | null): void
export declare function cacheGet(key: string): unknown
export declare function cacheDelete(key: string): boolean
export declare function cacheExists(key: string): boolean
export declare function cacheGetOrSet(key: string, default: JsJson, ttl?: number | undefined | null): unknown
export declare function cacheDeleteOrSet(key: string, value: JsJson, ttl?: number | undefined | null): unknown
export declare function cacheExistsOrSet(key: string, value: JsJson, ttl?: number | undefined | null): boolean
export declare function cacheDriver(): string
export declare function cacheClear(): void
export declare function cacheReset(): void
export declare class Settings {
  constructor()
  loadJson(path?: string | undefined | null, envName?: string | undefined | null, extraRoots?: Array<string> | undefined | null): void
  ensureLoaded(extraRoots?: Array<string> | undefined | null): void
  merge(values: unknown): void
  get(key: string, default?: unknown | undefined | null): unknown
  get host(): string
  get port(): number
  get debug(): boolean
  get reload(): boolean
  get env(): string
}
export declare class App {
  constructor()
  route(method: string, path: string, handler: (...args: any[]) => any): void
  listen(host: string, port: number): Promise<void>
}
